### ISSUE TITLE
Enhancing Security

### ISSUE THREAD

**Issue by SaddamBInSyed** [lewis-morris/TouchMouser#1]
@lewis-morris 

Thanks for your valuable work. 

tested and working fine on my win10 pc.

can you please advise what are the ways to enhance the security if we use this in production level.

kind note: I am only interested in mouse and keyboard functionalities. so I am expecting your reply with respect to these(mouse/keypad) functionalities.

please advise.

**Comment by lewis-morris** [comment]
I only put that message on there "just in case". I'm glad someone is putting it to good use. Are you using it just for personal use? 

Realistically if you are using it only on a local network there should be no security concerns unless some one has access to your network. Even then, because its a windows10 machine (and windows 10 is unable to run the bash scripts) the most anyone would be able to do is move your mouse and keyboard.

I haven't got the time to add extra security - but if I did (or you want to attempt it your self) I would.

1) create a database table to house user information - create a user and store a hashed a password
2) create a login form to log the user in 
3) create an additional api for the login
4) have the API return a JWT and store it somewhere locally on the page so it can be used.
5) tweek the existing API's to only authenticate with the correct JWT.
6) timeout the JWT after x requests and ask the user to login again / automatically send new tokens with requests so the user can stay logged in if they are not idle.

Also...

If you wanted to remove applications/media boxes you could quite easily amend the /static/home.html file (if you haven't already)

**Comment by SaddamBInSyed** [comment]
@lewis-morris 

While testing the app. seems when multi user connected to system (pc) then its seems flask server is handged ( no error on the terminal).

Is this known error?

pelase advise
